/**
 * ComplianceModal — shown once on first visit to acknowledge disclaimer.
 * Dismissed permanently via localStorage flag "cl_ack".
 */
import { useState, useEffect } from 'react';
import { ShieldCheck } from 'lucide-react';

export default function ComplianceModal() {
  const [show, setShow] = useState(false);

  useEffect(() => {
    const ack = localStorage.getItem('cl_ack');
    if (!ack) setShow(true);
  }, []);

  if (!show) return null;

  const handleDismiss = () => {
    localStorage.setItem('cl_ack', '1');
    setShow(false);
  };

  return (
    <div className="compliance-overlay">
      <div className="compliance-modal">
        <div className="compliance-icon">
          <ShieldCheck size={36} style={{ color: 'var(--accent)' }} />
        </div>
        <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 8, textAlign: 'center' }}>
          CrisisLens Intelligence Disclaimer
        </h3>
        <p style={{
          fontSize: 12, color: 'var(--text-2)', lineHeight: 1.6, textAlign: 'center',
          maxWidth: 360, marginBottom: 20,
        }}>
          CrisisLens opportunity signals are generated by quantitative models
          for <strong>informational and research purposes only</strong>.
          They do not constitute investment advice, solicitation, or
          recommendation to buy or sell any securities. Past performance
          and historical win rates are not indicative of future results.
        </p>
        <button className="compliance-btn" onClick={handleDismiss}>
          I Understand
        </button>
      </div>
    </div>
  );
}
